#!/usr/bin/env bash
# v1 mixed multi-client storm → kill -9 → recover/verify → CHECKPOINT → page-graph HTML.
#
# 1 DDL/CHECKPOINT client + 3 DML/DQL clients; 2 DBs × 2 tables; auto-commit oracle.
# Prefer MSYS2 bash on Windows (not WSL):
#   C:\msys64\usr\bin\bash.exe test-scripts/mixed_crash_page_graph.sh
#
# Env: DATA_DIR PORT HOST SEED TOTAL_OPS BUFFER_POOL_FRAMES PAGE_SIZE OUT_DIR TABLE_DIR OUT_HTML
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DATA_DIR="${DATA_DIR:-test/mixed-crash}"
PORT="${PORT:-9092}"
HOST="${HOST:-127.0.0.1}"
SEED="${SEED:-42}"
TOTAL_OPS="${TOTAL_OPS:-10000}"
BUFFER_POOL_FRAMES="${BUFFER_POOL_FRAMES:-1024}"
PAGE_SIZE="${PAGE_SIZE:-16384}"
OUT_DIR="${OUT_DIR:-out/mixed-crash}"
ORACLE_DIR="${OUT_DIR}/oracle"
TABLE_DIR="${TABLE_DIR:-${DATA_DIR}/shop/users}"
OUT_HTML="${OUT_HTML:-${OUT_DIR}/users.html}"
SERVER_PID=""

cleanup() {
  if [[ -n "${SERVER_PID}" ]] && kill -0 "${SERVER_PID}" 2>/dev/null; then
    kill "${SERVER_PID}" 2>/dev/null || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
}
trap cleanup EXIT

wait_for_port() {
  local host="$1" port="$2" tries="${3:-90}"
  local i
  for ((i = 1; i <= tries; i++)); do
    if (echo >/dev/tcp/"${host}"/"${port}") >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.5
  done
  echo "timed out waiting for ${host}:${port}" >&2
  return 1
}

free_port() {
  local port="$1"
  if command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -NoProfile -Command \
      "\$c = Get-NetTCPConnection -LocalPort ${port} -ErrorAction SilentlyContinue; if (\$c) { \$c | ForEach-Object { Stop-Process -Id \$_.OwningProcess -Force -ErrorAction SilentlyContinue } }" \
      >/dev/null 2>&1 || true
  elif command -v lsof >/dev/null 2>&1; then
    lsof -ti ":${port}" | xargs -r kill -9 2>/dev/null || true
  fi
  sleep 1
}

start_server() {
  echo "==> start server --data-dir ${DATA_DIR} --port ${PORT}"
  mvn -pl database-server exec:java \
    "-Dexec.args=--port ${PORT} --data-dir ${DATA_DIR}" &
  SERVER_PID=$!
  wait_for_port "${HOST}" "${PORT}"
}

run_harness() {
  local mode="$1"
  shift
  mvn -q -pl database-client exec:java \
    -Dclient.mainClass=com.example.client.MixedCrashHarness \
    -Dexec.interactive=false \
    "-Dexec.args=${mode} $*"
}

echo "==> free port ${PORT}"
free_port "${PORT}"

echo "==> wipe ${DATA_DIR}"
rm -rf "${DATA_DIR}"
mkdir -p "${DATA_DIR}" "${ORACLE_DIR}"

cat > "${DATA_DIR}/server.env" <<EOF
# Auto-generated by test-scripts/mixed_crash_page_graph.sh
CATALOG_LOCK_WAIT_SECONDS=30
CHECKPOINT_ENABLED=false
CHECKPOINT_STRATEGY=timeout
CHECKPOINT_TIMEOUT_SECONDS=300
MAX_WAL_SIZE_BYTES=16777216
PAGE_SIZE=${PAGE_SIZE}
INDEX_KEY_PADDING_BYTES=0
BUFFER_POOL_FRAMES=${BUFFER_POOL_FRAMES}
EOF

echo "==> mvn package"
mvn -q -DskipTests package

start_server

echo "==> mixed load (seed=${SEED} ops=${TOTAL_OPS}) — 1 DDL + 3 DML/DQL clients"
run_harness load "${HOST}" "${PORT}" "${SEED}" "${ORACLE_DIR}" "${TOTAL_OPS}"

echo "==> force-kill server pid=${SERVER_PID} (no flushAll)"
kill -9 "${SERVER_PID}" 2>/dev/null || true
wait "${SERVER_PID}" 2>/dev/null || true
SERVER_PID=""
sleep 1
free_port "${PORT}"

start_server

echo "==> verify SELECT == oracle after recovery"
run_harness verify "${HOST}" "${PORT}" "${SEED}" "${ORACLE_DIR}"

echo "==> final CHECKPOINT (durable pages for page-graph)"
run_harness checkpoint "${HOST}" "${PORT}"

echo "==> page graph → ${OUT_HTML}"
python tools/page-graph/page_graph.py --table-dir "${TABLE_DIR}" --out "${OUT_HTML}"

echo "==> done OK"
echo "    data:   ${DATA_DIR}"
echo "    oracle: ${ORACLE_DIR}"
echo "    html:   ${OUT_HTML}"
echo "    seed:   ${SEED}"
echo "    ops:    ${TOTAL_OPS}"
