#!/usr/bin/env bash
# Wipe test/data, load 1000 rows (8 KiB pages), CHECKPOINT, write page-graph HTML.
# Usage (from repo root, Git Bash / WSL / macOS / Linux):
#   bash scripts/run_1k_page_graph.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DATA_DIR="${DATA_DIR:-test/data}"
PORT="${PORT:-9090}"
PAGE_SIZE="${PAGE_SIZE:-8192}"
HOST="${HOST:-127.0.0.1}"
SCRIPT="${SCRIPT:-input/cmds/load_1k.txt}"
OUT_HTML="${OUT_HTML:-out/page-graph/users.html}"
TABLE_DIR="${TABLE_DIR:-${DATA_DIR}/shop/users}"
TRANSCRIPT_DIR="${TRANSCRIPT_DIR:-out}"
SERVER_PID=""

cleanup() {
  if [[ -n "${SERVER_PID}" ]] && kill -0 "${SERVER_PID}" 2>/dev/null; then
    kill "${SERVER_PID}" 2>/dev/null || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
}
trap cleanup EXIT

wait_for_port() {
  local host="$1" port="$2" tries="${3:-60}"
  local i
  for ((i = 1; i <= tries; i++)); do
    if (echo >/dev/tcp/"${host}"/"${port}") >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.5
  done
  echo "timed out waiting for ${host}:${port}" >&2
  return 1
}

# Free PORT if an old server is still bound (common on Windows after a prior run).
free_port() {
  local port="$1"
  if command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -NoProfile -Command \
      "\$c = Get-NetTCPConnection -LocalPort ${port} -ErrorAction SilentlyContinue; if (\$c) { \$c | ForEach-Object { Stop-Process -Id \$_.OwningProcess -Force -ErrorAction SilentlyContinue } }" \
      >/dev/null 2>&1 || true
  elif command -v lsof >/dev/null 2>&1; then
    lsof -ti ":${port}" | xargs -r kill -9 2>/dev/null || true
  fi
  sleep 1
}

echo "==> free port ${PORT} (if occupied)"
free_port "${PORT}"

echo "==> wipe + create ${DATA_DIR}"
rm -rf "${DATA_DIR}"
mkdir -p "${DATA_DIR}" "${TRANSCRIPT_DIR}" out/page-graph

# UTF-8 without BOM (BOM breaks the first SQL token on Windows tools).
cat > "${DATA_DIR}/server.env" <<EOF
# Auto-generated by scripts/run_1k_page_graph.sh
CATALOG_LOCK_WAIT_SECONDS=30
CHECKPOINT_ENABLED=true
CHECKPOINT_STRATEGY=timeout
CHECKPOINT_TIMEOUT_SECONDS=300
MAX_WAL_SIZE_BYTES=16777216
PAGE_SIZE=${PAGE_SIZE}
EOF

printf 'CHECKPOINT\n' > "${TRANSCRIPT_DIR}/.checkpoint.txt"

echo "==> mvn package"
mvn -q -DskipTests package

echo "==> start server --data-dir ${DATA_DIR} --port ${PORT}"
mvn -pl database-server exec:java \
  "-Dexec.args=--port ${PORT} --data-dir ${DATA_DIR}" &
SERVER_PID=$!
wait_for_port "${HOST}" "${PORT}"

echo "==> load 1k (${SCRIPT})"
mvn -pl database-client exec:java \
  "-Dexec.args=--script ${SCRIPT} --out ${TRANSCRIPT_DIR}/load_1k.run.txt ${HOST} ${PORT}"

echo "==> CHECKPOINT (flush dirty pages to disk for page-graph)"
mvn -pl database-client exec:java \
  "-Dexec.args=--script ${TRANSCRIPT_DIR}/.checkpoint.txt --out ${TRANSCRIPT_DIR}/checkpoint.run.txt ${HOST} ${PORT}"

echo "==> page graph → ${OUT_HTML}"
python tools/page-graph/page_graph.py --table-dir "${TABLE_DIR}" --out "${OUT_HTML}"

echo "==> done"
echo "    data:  ${DATA_DIR}"
echo "    table: ${TABLE_DIR}"
echo "    html:  ${OUT_HTML}"
echo "    open:  file:///${ROOT//\\//}/${OUT_HTML}"
